# Generated by Django 3.0.3 on 2020-02-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50)),
                ('choice', models.CharField(choices=[('beavis.zen', 'beavis.zen'), ('blowfish', 'blowfish'), ('bong', 'bong'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('cheese', 'cheese'), ('cower', 'cower'), ('daemon', 'daemon'), ('default', 'default'), ('dragon-and-cow', 'dragon-and-cow'), ('dragon', 'dragon'), ('elephant-in-snake', 'elephant-in-snake'), ('elephant', 'elephant'), ('eyes', 'eyes'), ('flaming-sheep', 'flaming-sheep'), ('ghostbusters', 'ghostbusters'), ('kitty', 'kitty'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('mutilated', 'mutilated'), ('satanic', 'satanic'), ('sodomized', 'sodomized'), ('surgery', 'surgery'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('turkey', 'turkey'), ('turtle', 'turtle'), ('tux', 'tux'), ('www', 'www')], max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowsay.Author')),
            ],
        ),
    ]
