# Generated by Django 3.0.3 on 2020-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_auto_20200220_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text',
            field=models.CharField(blank=True, default='Speak', max_length=50),
        ),
    ]
