# Generated by Django 3.0.3 on 2020-02-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_auto_20200221_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='parent',
        ),
    ]
