# Generated by Django 3.0.3 on 2020-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0006_auto_20200220_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='choice',
            field=models.CharField(choices=[('beavis.zen', 'beavis.zen'), ('blowfish', 'blowfish'), ('bong', 'bong'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('cheese', 'cheese'), ('cower', 'cower'), ('daemon', 'daemon'), ('default', 'default'), ('dragon-and-cow', 'dragon-and-cow'), ('dragon', 'dragon'), ('elephant-in-snake', 'elephant-in-snake'), ('elephant', 'elephant'), ('eyes', 'eyes'), ('flaming-sheep', 'flaming-sheep'), ('ghostbusters', 'ghostbusters'), ('kitty', 'kitty'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('mutilated', 'mutilated'), ('satanic', 'satanic'), ('sodomized', 'sodomized'), ('surgery', 'surgery'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('turkey', 'turkey'), ('turtle', 'turtle'), ('tux', 'tux'), ('www', 'www')], max_length=17),
        ),
    ]
